allowed:
    origins: http://localhost:4200

klaus404:
    expensemanager:
        jwtCookieName: klaus
        jwtExpirationMs: 86400000
        jwtSecret: thisisasecretpassword

logging:
    level:
        org:
            springframework:
                security: DEBUG

okta:
    oauth2:
        client-id: 0oad1f3lv4csZUKQ35d7
        client-secret: fPfl0fTD3f4ngWp11pBDY0uTcBCL4CPWP9A3Rk-Zo2ugaapH2Wy6kEyzfljNXkwQ
        issuer: https://dev-42527963.okta.com/oauth2/default
        redirect-uri: http://localhost:8080/authorization-code/callback
        post-logout-redirect-uri: http://localhost:8080/logout/callback

server:
    error:
        include-message: always

spring:
    data:
        rest:
            base-path: /
    datasource:
        password: caramelsarat
        url: jdbc:postgresql://localhost:5432/expensemanager
        username: expenseadmin
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    security:
        oauth2:
            resource-server:
                jwt:
                    issuer-uri: https://dev-42527963.okta.com/oauth2/default
            client:
                registration:
                    internal-client:
                        provider: okta
                        authorization-grant-type: client_credentials
                        scope: openid, profile, email, offline_access
                        client-id: 0oad1f3lv4csZUKQ35d7
                        client-secret: fPfl0fTD3f4ngWp11pBDY0uTcBCL4CPWP9A3Rk-Zo2ugaapH2Wy6kEyzfljNXkwQ
